version: 0.2

phases:
  install:
    commands:
      - echo "Starting the build process..."
  build:
    commands:
      - echo "Listing all files in the repo:"
      - ls -al
      - echo "Build successful!"

artifacts:
  files:
    - '**/*'

